name: lca_sweng
description: A demonstration of a Binary Tree and Directed Acyclic Graph implementation, with a command line app for the Binary Tree
version: 1.0.0

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.18.2
